name: LMS Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Data Generator
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python generate_data.py
