name: LMS Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Generator
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python generate_data.py

      - name: Done
        run: echo "ETL Pipeline Completed Successfully"    sudo apt-get install -y mongodb-mongosh

      - name: Run Analytics Pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: mongosh "$MONGO_URI" run_analytics.js

      - name: Done
        run: echo "ETL + Analytics completed"
